### ISSUE TITLE
Add support for google models

### ISSUE THREAD

**Issue by mafaldcostad** [TonicAI/tonic_validate#114]
Pls add support to use PALM and Gemini as the LLM to do the evaluation

**Comment by akamor** [comment]
@mafaldcostad We'll get started on this in next day or two.  Expect it released by EOW or early next week.

**Comment by akamor** [comment]
@mafaldcostad  Are you planning on using just the SDK or are you also using a validate.tonic.ai account for visualizations?

**Comment by mafaldcostad** [comment]
> @mafaldcostad Are you planning on using just the SDK or are you also using a validate.tonic.ai account for visualizations?

Hi Adam! I am planning on using just the SDK
