### ISSUE TITLE
Support history display in tonic_validate UI

### ISSUE THREAD

**Issue by chansonzhang** [TonicAI/tonic_validate#143]
When we eval the performance of agent in llama-index, we will include a chat history in each test case. If those chat histories can be displayed in the tonic_validate UI, it will be very helpful.

**Comment by akamor** [comment]
This is a good idea.  Would you mind shooting us an email at validate@tonic.ai.  I'd like to chat a bit over email about your use case so we can make sure we build the correct experience.

**Comment by chansonzhang** [comment]
> This is a good idea. Would you mind shooting us an email at [validate@tonic.ai](mailto:validate@tonic.ai). I'd like to chat a bit over email about your use case so we can make sure we build the correct experience.

Thanks for your quick response. I've sent you an email, please have a look.
