### ISSUE TITLE
Python3.8 imcompatible typing

### ISSUE THREAD

**Issue by logan-markewich** [TonicAI/tonic_validate#35]
Tonic seems to support python3.8 judging by the pyproject.toml, but looks like some incompatible typing that breaks python3.8 or less

```
/home/runner/.cache/pants/named_caches/pex_root/venvs/s/5ac6c5cf/venv/lib/python3.8/site-packages/tonic_validate/classes/llm_response.py:10: in LLMResponse
    llm_context_list: list[str]
E   TypeError: 'type' object is not subscriptable
```

Need to type with
`from typing import List`

**Comment by ethan-tonic** [comment]
Thanks for catching this! I put out a PR to fix it
