### ISSUE TITLE
When OpenAI evaluator errors out sometimes, the integrity of the entire benchmark results come into question

### ISSUE THREAD

**Issue by adorosario** [TonicAI/tonic_validate#36]
https://github.com/TonicAI/tonic_validate/blob/058ed170d6f3666f15f398a5349732c9f7a80a2f/tonic_validate/validate_scorer.py#L44

So one problem we are seeing is, when the OpenAI evaluator call errors out (and returns 0 say), the full benchmark results come into question. 

For example, if we run the full PaulGrahamEssayDataset dataset with 44 questions, we will notice that some of the metrics are straight out 0 -- because the OpenAI evaluator errored out (for whatever reason). This put the final overall scores into question. 

To get around this, we had to NOT send all the 44 responses in one call to `scorer.score_run` -- but rather do it one at a time and check to make sure the evaluator has not errored out. However, this approach is not ideal. 

What would be nice is if the error checking for the evaluator (say via a retries mechanism) happens in tonic_validate/utils/llm_calls.py - so that resiliency is captured at that level. 

The reason this is critical is because there is a big difference between a score of "0" and "error" when it comes to the final benchmarking results.

**Comment by ethan-tonic** [comment]
Thanks for pointing this out. We will get this fixed. Out of curiosity, do you all have a preference between just throwing out the whole benchmark if it errors out or just scoring the ones that didn't error out? Because one could argue if 2 out of 44 questions fail then scoring out of 42 questions still compromises the integrity of the results

**Comment by adorosario** [comment]
> Thanks for pointing this out. We will get this fixed. Out of curiosity, do you all have a preference between just throwing out the whole benchmark if it errors out or just scoring the ones that didn't error out? Because one could argue if 2 out of 44 questions fail then scoring out of 42 questions still compromises the integrity of the results since you're averaging over a different number of questions

My preference would be to just score the ones that didn't error out. But a good case could be made for either option. 

But there is also a bigger issue -- which is: For certain metrics like `AnswerConsistencyBinaryMetric` -- a value of 0 means "false" .. so when an error is equated with that, that can really affect the benchmark. 

For example, say two LLMs are being compared and one of them gets lucky and gets lots of errors for `AnswerConsistencyBinaryMetric` -- now everyone will think "Wow - look at how awesome that LLM is at hallucination". 

So for ultra-sensitive metrics like that, I would certainly like an error condition to NOT be counted in the final score. 

PS: You guys are doing great work by the way -- thank you!

**Comment by ethan-tonic** [comment]
Put out a PR to fix this issue. By default, it will now return `None` when a metric has failed to be scored and calculates the overall scores based on all the metrics that don't have `None` for their values. It also adds a `fail_on_error` to the `ValidateScorer` constructor to allow you to change this behavior to instead throw an exception if a metric fails to be scored.
