### ISSUE TITLE
Anti-Hallucination Score - Switched?

### ISSUE THREAD

**Issue by adorosario** [TonicAI/tonic_validate#37]
https://github.com/TonicAI/tonic_validate/blob/058ed170d6f3666f15f398a5349732c9f7a80a2f/tonic_validate/utils/llm_calls.py#L90C5-L97C6

Guys -- is it possible that this code has switched the metric value? 

So: `If the answer contains information that cannot be attributed to the context then respond with true.`

This means: When there IS hallucination, the score is "1". 

While the metric signifies "anti-hallucination" -- which means high scores are good, low scores are bad. 

https://docs.tonic.ai/validate/about-rag-metrics/tonic-validate-rag-metrics-reference

```
Answer consistency binary
from tonic_validate.metrics import AnswerConsistencyBinaryMetric
Answer consistency binary indicates whether all of the information in the answer is derived from the retrieved context.
If all of the information in the answer comes from the retrieved context, then the answer is consistent with the context, and the value of this metric is 1.
If the answer contains information that is not derived from the context, then the value of this metric is 0.
To calculate answer consistency binary, we ask an LLM whether the RAG system answer contains any information that is not derived from the context.
Answer consistency binary is a binary integer.
```

https://github.com/TonicAI/tonic_validate/blob/main/tonic_validate/metrics/answer_consistency_binary_metric.py#L11C7-L11C36

```
Returns
        -------
        int
            0 if there is information in answer not derived from context in context_list
            1 otherwise
```

https://github.com/TonicAI/tonic_validate/blob/main/tonic_validate/utils/llm_calls.py#L90C5-L97C6
```
main_message = (
        "Considering the following list of context and then answer, which answers a"
        "user's query using the context, determine whether the answer contains any"
        "information that can not be attributed to the intormation in the list of"
        "context. If the answer contains information that cannot be attributed to the"
        "context then respond with true. Otherwise response with false. Response with"
        "either true or false and no additional text."
    )
```

**Comment by joeferraratonic** [comment]
@adorosario This is now fixed and released in version 3.0.1. Thanks again for catching this!
