### ISSUE TITLE
500 error when passing data to the dashboard using validate_api

### ISSUE THREAD

**Issue by ojpetar** [TonicAI/tonic_validate#42]
Hey - noticed a problem when trying to log the run results using validate_api
`[/usr/local/lib/python3.10/dist-packages/tonic_validate/validate_api.py](https://e2y0hisynxp-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240212-060142_RC00_606195215#) in upload_run(self, project_id, run, run_metadata)
     57         )
     58         for run_data in run.run_data:
---> 59             _ = self.client.http_post(
     60                 f"/projects/{project_id}/runs/{run_response['id']}/logs",
     61                 data=run_data.to_dict(),

[/usr/local/lib/python3.10/dist-packages/tonic_validate/utils/http_client.py](https://e2y0hisynxp-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240212-060142_RC00_606195215#) in http_post(self, url, params, data)
     61             verify=False,
     62         )
---> 63         res.raise_for_status()
     64         return res.json()
     65 

[/usr/local/lib/python3.10/dist-packages/requests/models.py](https://e2y0hisynxp-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240212-060142_RC00_606195215#) in raise_for_status(self)
   1019 
   1020         if http_error_msg:
-> 1021             raise HTTPError(http_error_msg, response=self)
   1022 
   1023     def close(self):

HTTPError: 500 Server Error: Internal Server Error for url: https://validate.tonic.ai/api/v1/projects/projId/runs/runId/logs`

Here's our input:
scorer = ValidateScorer([AnswerConsistencyMetric(), AnswerConsistencyBinaryMetric(), AugmentationPrecisionMetric(), AugmentationAccuracyMetric(), RetrievalPrecisionMetric()])
run = scorer.score(benchmark, get_llm_response)

**Comment by akamor** [comment]
Thanks @ojpetar. 

Its not clear from the code snippet but I reviewed our logs and this happened during a run where you were using our AnswerSimilarityMetric but not setting an 'answer' in your benchmark. We'll get this fixed ASAP.  In the meantime, for anyone else encountered the same issue make sure to construct your benchmark as:

```
Benchmark(questions=["question1", "question2", ...], answers=["", "", ...])
```
when you are just having Validate score the answer against its context and do not provide reference answers.  In our fix we will do away with the need to specify an answers param at all to the Benchmark constructor.

**Comment by ojpetar** [comment]
Awesome that worked! Thanks so much 🚀

**Comment by ethan-tonic** [comment]
We fixed this on our backend. We should have the server updated tonight to fix the issue
