### ISSUE TITLE
Request for OpenAI Assistant Examples

### ISSUE THREAD

**Issue by williamzebrowskI** [TonicAI/tonic_validate#91]
This is not an issue but a request for further examples associated with testing OpenAI Assistants. 

Currently, there is one example which compares a CustomGPT vs Assistant but I was looking for more if possible.  The example shows the use of AnswerSimilarityMetric and curious if there are anymore examples you can share on Validating an Assistants performance using other metrics.  

Thanks!

**Comment by akamor** [comment]
If all of this makes sense and you are good just let me know so we can close out the issue.

**Comment by akamor** [comment]
Closing for now but happy to re-open if you still have questions @williamzebrowskI
